robot_paths:
  - name: path0
    waypoints:
      - [30.0, 30.0, 0.0]
      - [-30.0, -30.0, 60.0]

  - name: path1
    waypoints:
      - [-30.0, -30.0, 0.0]
      - [30.0, 30.0, 60.0]

  - name: path2
    waypoints:
      - [30.0, -30.0, 60.0]
      - [-30.0, 30.0, 0.0]

  - name: path3
    waypoints:
      - [-30.0, 30.0, 60.0]
      - [30.0, -30.0, 0.0]

  - name: path4
    waypoints:
      - [-30.0, -30.0, 60.0]
      - [30.0, 30.0, 0.0]

  - name: path5
    waypoints:
      - [30.0, 30.0, 60.0]
      - [-30.0, -30.0, 0.0]

  - name: path6
    waypoints:
      - [-30.0, 30.0, 0.0]
      - [30.0, -30.0, 60.0]

  - name: path7
    waypoints:
      - [30.0, -30.0, 0.0]
      - [-30.0, 30.0, 60.0]