robot_paths:
  - name: path0
    waypoints:
      - [10.0, 10.0, 0.0]
      - [-10.0, -10.0, 20.0]

  - name: path1
    waypoints:
      - [-10.0, -10.0, 0.0]
      - [10.0, 10.0, 20.0]

  - name: path2
    waypoints:
      - [10.0, -10.0, 20.0]
      - [-10.0, 10.0, 0.0]

  - name: path3
    waypoints:
      - [-10.0, 10.0, 20.0]
      - [10.0, -10.0, 0.0]

  - name: path4
    waypoints:
      - [-10.0, -10.0, 20.0]
      - [10.0, 10.0, 0.0]

  - name: path5
    waypoints:
      - [10.0, 10.0, 20.0]
      - [-10.0, -10.0, 0.0]

  - name: path6
    waypoints:
      - [-10.0, 10.0, 0.0]
      - [10.0, -10.0, 20.0]

  - name: path7
    waypoints:
      - [10.0, -10.0, 0.0]
      - [-10.0, 10.0, 20.0]