robot_paths:
  - name: path0
    waypoints:
      - [-20.0, 25.0, 20.0]
      - [20.0, 50.0, 20.0]

  - name: path1
    waypoints:
      - [-10.0, 25.0, 20.0]
      - [10.0, 50.0, 20.0]

  - name: path2
    waypoints:
      - [0.0, 25.0, 20.0]
      - [0.0, 50.0, 20.0]

  - name: path3
    waypoints:
      - [10.0, 25.0, 20.0]
      - [-10.0, 50.0, 20.0]

  - name: path4
    waypoints:
      - [20.0, 25.0, 20.0]
      - [-20.0, 50.0, 20.0]

  - name: path5
    waypoints:
      - [-20.0, 50.0, 20.0]
      - [20.0, 25.0, 20.0]

  - name: path6
    waypoints:
      - [-10.0, 50.0, 20.0]
      - [10.0, 25.0, 20.0]

  - name: path7
    waypoints:
      - [0.0, 50.0, 20.0]
      - [0.0, 25.0, 20.0]

  - name: path8
    waypoints:
      - [10.0, 50.0, 20.0]
      - [-10.0, 25.0, 20.0]

  - name: path9
    waypoints:
      - [20.0, 50.0, 20.0]
      - [-20.0, 25.0, 20.0]




























